export {
  ONBOARDING_INDUSTRIES as REGISTER_INDUSTRIES,
  ONBOARDING_TEAM_SIZES as REGISTER_TEAM_SIZES,
  ONBOARDING_REVENUE_OPTIONS as REGISTER_REVENUE_OPTIONS,
  ONBOARDING_CUSTOMER_SOURCES as REGISTER_CUSTOMER_SOURCES,
  ONBOARDING_SOCIAL_CHANNELS as REGISTER_SOCIAL_CHANNELS,
  ONBOARDING_PRIMARY_GOALS as REGISTER_PRIMARY_GOALS,
  ONBOARDING_WIZARD_STEPS as REGISTER_WIZARD_STEPS,
  INITIAL_ONBOARDING_WIZARD_DATA as INITIAL_REGISTER_WIZARD_DATA,
  type OnboardingIndustry as RegisterIndustry,
  type OnboardingTeamSize as RegisterTeamSize,
  type OnboardingRevenue as RegisterRevenue,
  type OnboardingCustomerSource as RegisterCustomerSource,
  type OnboardingSocialChannel as RegisterSocialChannel,
  type OnboardingPrimaryGoal as RegisterPrimaryGoal,
  type OnboardingWizardStep as RegisterWizardStep,
  type OnboardingWizardData as RegisterWizardData,
  type WebsiteAnalysisResult,
} from '@/lib/onboarding-wizard/constants';
